# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Check CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ["*"]

jobs:
  check-clang-format:
    name: Check clang-format

    runs-on: ubuntu-24.04
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Check with clang-format
        shell: bash --noprofile --norc -euo pipefail {0}
        run: "git ls-files '*.c' '*.cpp' '*.h' '*.hpp' | xargs --no-run-if-empty clang-format --dry-run --Werror"

  check-gersemi:
    name: Check gersemi

    runs-on: ubuntu-slim
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install gersemi with setup-python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"
          pip-install: gersemi

      - name: Check with gersemi
        shell: bash --noprofile --norc -euo pipefail {0}
        run: "git ls-files CMakeLists.txt '*.cmake' | xargs --no-run-if-empty gersemi --check"

  check-reuse:
    name: Check reuse

    runs-on: ubuntu-24.04
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install reuse with setup-python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"
          pip-install: reuse

      - name: Lint with reuse
        shell: bash --noprofile --norc -euo pipefail {0}
        run: reuse lint
