# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Library CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ["*"]

jobs:
  build:
    name: Build and Test Library

    runs-on: ubuntu-24.04
    timeout-minutes: 30

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Configure
        shell: bash --noprofile --norc -euo pipefail {0}
        run: cmake --preset default

      - name: Build
        shell: bash --noprofile --norc -euo pipefail {0}
        run: cmake --build --preset default

      - name: Test
        shell: bash --noprofile --norc -euo pipefail {0}
        run: ctest --preset default --output-on-failure
